module.exports.pt = {
  company_of_interest: "Empresa de Interesse",
  supplier: "Fornecedor",
  customer: "Cliente",
  intermediary: "Intermediário",
  customer_customer: "Cliente do Cliente",
  aggregator: "Agregador",
  business_relationship: "Relação comercial",
  or: "OU",
  xor: "XOU",
  text: "Texto",
  save: "Salvar",
  delete: "Deletar",
  export: "Exportar",
  zoomin: "Zoom mais",
  zoomout: "Zoom menos",
  zoomDefault: "Zoom padrão",

  recort:"Recortar",
  copy:"Copiar",
  colar:"Colar",
  desfazer:"Desfazer",
  refazer:"Refazer",
  all:"Selecionar Tudo",
  desfazer_selecao:"Desfazer Seleção",
  print:"Imprimir",
  visualizar:"Visualizar",
  propriedades:"Propriedades XML",
  estatisticas:"Estatísticas do modelo",
  relacionamentos:"Relacionamentos",
  agrupar:"Agrupar",
  desagrupar:"Desagrupar",
  tras:"Para Trás",
  frente: "Para Frente",
  negrito:"Negrito",
  sublinhado:"Sublinhado",
  italico:"Itálico",
  export_png :"Exportar em PNG",
  export_svg:"Exportar em SVG",
  export_xml:"Exportar em XML",
  export_json:"Exportar em JSON",
  import:"Importar XML",
  import2:"Importar Arquivo XML",
  cancel:"Cancelar",
  importar:"Importar",
  baixar:"Baixar Arquivo",
  imagem_PNG:"Baixar Imagem em PNG",
  imagem_SVG:"Baixar Imagem em SVG",
  xml:"Baixar em XML",
  json:"Baixar em JSON",
  sair:"Sair",
  
};

module.exports.en = {
  company_of_interest: "Company of Interest",
  supplier: "Provider",
  customer: "Client",
  intermediary: "Intermediary",
  customer_customer: "Customer's Customer",
  aggregator: "Aggregator",
  business_relationship: "Business Relationship",
  or: "OR",
  xor: "XOR",
  text: "Text",
  save: "Save",
  delete: "Delete",
  export: "Export",
  zoomin: "Zoom in",
  zoomout: "Zoom out",
  zoomDefault: "Zoom default",

  recort:"Cut",
  copy:"Copy",
  colar:"Paste",
  desfazer:"Undo",
  refazer:"Redo",
  all:"Select All",
  desfazer_selecao:"Undo Selection",
  print:"Print Out",
  visualizar:"To View",
  propriedades:"Properties XML",
  estatisticas:"Model statistics",
  relacionamentos:"Relationships",
  agrupar:"Agroup",
  desagrupar:"Ungroup",
  tras:"To Back",
  frente: "To Front",
  negrito:"Bold",
  sublinhado:"Underline",
  italico:"Italic",


  export_png :"Export in PNG",
  export_svg:"Export in SVG",
  export_xml:"Export in XML",
  export_json:"Export in JSON",
  import:"Import XML",
  import2:"Import XML File",
  cancel:"Cancel",
  importar:"Import",
  baixar:"Download file",
  imagem_PNG:"Download PNG Image",
  imagem_SVG:"Download SVG Image",
  xml:"Download in XML",
  json:"Download in JSON",
  sair:"Get out"
};

module.exports.es = {
  company_of_interest: "Empresa de Interés",
  supplier: "Proveedor",
  customer: "Cliente",
  intermediary: "Intermediario",
  customer_customer: "Cliente del Cliente",
  aggregator: "Agregador",
  business_relationship: "Relación de Negocios",
  or: "O",
  xor: "XOR",
  text: "Texto",
  save: "Salvar",
  save: "Salvar",
  delete: "Deletar",
  export: "Exportar",
  zoomin: "Zoom mais",
  zoomout: "Zoom menos",
  zoomDefault: "Zoom padrão",

  recort:"Recorte",
  copy:"Dupdo",
  colar:"Pegar",
  desfazer:"Deshacer",
  refazer:"Rehacer",
  all:"Seleccionar Todo",
  desfazer_selecao:"Deshacer Selección",
  print:"Imprimir",
  visualizar:"Para ver",
  propriedades:"Propiedades XML",
  estatisticas:"Estadísticas del modelo",
  relacionamentos:"Relaciones",
  agrupar:"Un Grupo",
  desagrupar:"Desagrupar",
  tras:"Volver",
  frente: "Al frente",
  negrito:"Negrito",
  sublinhado:"Subrayar",
  italico:"Itálico",



  export_png :"Exportar en PNG",
  export_svg:"Exportar en SVG",
  export_xml:"Exportar en XML",
  export_json:"Exportar en JSON",
  import:"Importar XML",

  import2:"Importar archivo XML",
  cancel:"Cancelar",
  importar:"Importar",
  baixar:"Descargar archivo",
  imagem_PNG:"Descargar imagen PNG",
  imagem_SVG:"Descargar imagen SVG",
  xml:"Descarga en XML",
  json:"Descarga en JSON",
  sair:"Sal"
  
  
};
