module.exports.pt = {
  company_of_interest: "Empresa de Interesse",
  supplier: "Fornecedor",
  customer: "Cliente",
  intermediary: "Intermediário",
  customer_customer: "Cliente do Cliente",
  aggregator: "Agregador",
  business_relationship: "Relação comercial",
  or: "OU",
  xor: "XOU",
  text: "Texto",
  save: "Salvar",
  export: "Exportar",
  zoomin: "Zoom mais",
  zoomout: "Zoom menos",
  zoomDefault: "Zoom padrão",
  recort: "Recortar",
  copy: "Copiar",
  colar: "Colar",
  desfazer: "Desfazer",
  refazer: "Refazer",
  all: "Selecionar Tudo",
  desfazer_selecao: "Desfazer Seleção",
  print: "Imprimir",
  visualizar: "Visualizar",
  propriedades: "Propriedades XML",
  estatisticas: "Estatísticas do modelo",
  relacionamentos: "Relacionamentos",
  agrupar: "Agrupar",
  desagrupar: "Desagrupar",
  tras: "Para Trás",
  frente: "Para Frente",
  negrito: "Negrito",
  sublinhado: "Sublinhado",
  italico: "Itálico",
  export_png: "Exportar em PNG",
  export_svg: "Exportar em SVG",
  export_xml: "Exportar em XML",
  export_json: "Exportar em JSON",
  import: "Importar XML",
  import2: "Importar Arquivo XML",
  cancel: "Cancelar",
  importar: "Importar",
  baixar: "Baixar Arquivo",
  imagem_PNG: "Baixar Imagem em PNG",
  imagem_SVG: "Baixar Imagem em SVG",
  xml: "Baixar em XML",
  json: "Baixar em JSON",
  sair: "Sair",
  login: "Realizar login",
  publicModels: "Modelos público",
  privateModels: "Meus modelos",
  sub: "Modele ecossistemas de software",
  about: "Sobre",
  models: "Modelos",
  openEditor: "Abrir no editor",
  loadModelErro: "Ocorreu um erro ao carregar os modelos",
  update: "atualizar",
  delete: "excluir",
  updateSucess: "Modelo atualizado",
  deleteSuccess: "Modelo deletado",
  register: "Cadastro",
  autor: "Autor",
  details: "Ver detalhes",
  title: "Titulo",
  description: "Descrição",
  createAt: "Criado em",
  updateAt: "Última atualização",

  routes: {
    home: "/pt-br/",
    editor: "/pt-br/editor",
    publicModels: "/pt-br/modelos",
    privateModels: "/pt-br/modelos/privado",
    register: "/pt-br/cadastro",
    login: "/pt-br/login",
    modelEditor: "/pt-br/editor/:codigo",
  },
};

module.exports.en = {
  company_of_interest: "Company of interest",
  supplier: "Provider",
  customer: "Client",
  intermediary: "Intermediary",
  customer_customer: "Customer customer",
  aggregator: "Aggregator",
  business_relationship: "Commercial relationship",
  or: "OR",
  xor: "Xou",
  text: "Text",
  save: "To save",
  export: "Export",
  zoomin: "Zoom More",
  zoomout: "Zoom less",
  zoomDefault: "Standard Zoom",
  recort: "Cut out",
  copy: "Copy",
  colar: "Necklace",
  desfazer: "Undo",
  refazer: "Redo",
  all: "Select all",
  desfazer_selecao: "Undel selection",
  print: "Print out",
  visualizar: "To view",
  propriedades: "XML Properties",
  estatisticas: "Model Statistics",
  relacionamentos: "Relationships",
  agrupar: "Agroup",
  desagrupar: "Disagreeing",
  tras: "Back",
  frente: "Forward",
  negrito: "Bold",
  sublinhado: "Underlined",
  italico: "Italic",
  export_png: "Export in PNG",
  export_svg: "Export in SVG",
  export_xml: "Export in XML",
  export_json: "Export in JSON",
  import: "Import XML",
  import2: "Import XML File",
  cancel: "Cancel",
  importar: "Import",
  baixar: "Download file",
  imagem_PNG: "Download PNG Image",
  imagem_SVG: "Download Image in SVG",
  xml: "Download in XML",
  json: "Download in Json",
  sair: "Go out",
  login: "Login",
  publicModels: "Public models",
  privateModels: "My models",
  sub: "Model Software Ecosystems",
  about: "About",
  models: "Models",
  openEditor: "Open in the editor",
  loadModelErro: "An error occurred when loading the models",
  update: "update",
  delete: "delete",
  updateSucess: "Updated Model",
  deleteSuccess: "Deleted Model",
  register: "Registration",
  autor: "Author",
  details: "See details",
  title: "Title",
  description: "Description",
  createAt: "Created in",
  updateAt: "Last update",

  routes: {
    home: "/en/",
    editor: "/en/editor",
    publicModels: "/en/modelos",
    privateModels: "/en/modelos/privado",
    register: "/en/cadastro",
    login: "/en/login",
    modelEditor: "/en/editor/:codigo",
  },
};

module.exports.pt = {
  company_of_interest: "Compañía de interés",
  supplier: "Proveedor",
  customer: "Cliente",
  intermediary: "Intermediario",
  customer_customer: "Cliente de cliente",
  aggregator: "Agregador",
  business_relationship: "Relación comercial",
  or: "O",
  xor: "Xou",
  text: "Texto",
  save: "Ahorrar",
  export: "Exportar",
  zoomin: "Zoom más",
  zoomout: "Zoom menos",
  zoomDefault: "Zoom estándar",
  recort: "Separar",
  copy: "Copiar",
  colar: "Collar",
  desfazer: "Deshacer",
  refazer: "Rehacer",
  all: "Seleccionar todo",
  desfazer_selecao: "Selección de Undel",
  print: "Imprimir",
  visualizar: "Para ver",
  propriedades: "Propiedades XML",
  estatisticas: "Estadísticas del modelo",
  relacionamentos: "Relaciones",
  agrupar: "Un grupo",
  desagrupar: "En desacuerdo",
  tras: "Para atrás",
  frente: "Adelante",
  negrito: "Audaz",
  sublinhado: "Subrayada",
  italico: "Itálico",
  export_png: "Exportar en PNG",
  export_svg: "Exportar en SVG",
  export_xml: "Exportar en XML",
  export_json: "Exportación en JSON",
  import: "Importar xml",
  import2: "Importar archivo XML",
  cancel: "Cancelar",
  importar: "Importar",
  baixar: "Descargar archivo",
  imagem_PNG: "Descargar imagen PNG",
  imagem_SVG: "Descargar imagen en SVG",
  xml: "Descargar en XML",
  json: "Descargar en json",
  sair: "Salir",
  login: "Acceso",
  publicModels: "Modelos públicos",
  privateModels: "Mis modelos",
  sub: "Ecosistemas de software modelo",
  about: "Sobre",
  models: "Modelos",
  openEditor: "Abrir en el editor",
  loadModelErro: "Se produjo un error al cargar los modelos",
  update: "actualizar",
  delete: "Eliminar",
  updateSucess: "Modelo actualizado",
  deleteSuccess: "Modelo eliminado",
  register: "Registro",
  autor: "Autor",
  details: "Ver detalles",
  title: "Título",
  description: "Descripción",
  createAt: "Creado en",
  updateAt: "Última actualización",

  routes: {
    home: "/es/",
    editor: "/es/editor",
    publicModels: "/es/modelos",
    privateModels: "/es/modelos/privado",
    register: "/es/cadastro",
    login: "/es/login",
    modelEditor: "/es/editor/:codigo",
  },
};
